import type { Metadata } from "next";
import {Vazirmatn} from "next/font/google";
import "./globals.css";
import Themeprovider from "../../components/theme/Themeprovider";



const Vazir = Vazirmatn({
  variable: "--font-vazir-sans",
  subsets: ["latin","arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <Themeprovider>
      <body className={`${Vazir.variable}`}>
        {children}
      </body>
      </Themeprovider>
    </html>
  );
}
